### ISSUE TITLE
AWS CLI profiles

### ISSUE THREAD

**Issue by nickday** [jenslauterbach/ddbt#9]
This looks super useful but I'm having issues with using a specific AWS profile - I have several set up on my machine and need this script to use a specific one.

I have tried doing `export AWS_DEFAULT_PROFILE=xxx` before running (to switch the shell over to the profile I want to use), but the script reports that the table cannot be found. In the same shell `aws dynamodb list-tables` does list the table correctly.

Alternatively maybe a `--profile` option be added into the script?

**Comment by nickday** [comment]
Ah, `export AWS_PROFILE=xxx` did it! 👍

**Comment by jenslauterbach** [comment]
Hi @nickday 👋 ,

thank you for opening this issue. I am glad you found a way to fix your issue. I am indeed planning to add a `--profile` option to make all of this more explicit. 

If you this is still interesting for you, you can follow issue #10.
